name: globesisters_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  octo_image: ^1.0.2
  cached_network_image: ^3.2.2
  faker: ^2.0.0
  like_button: ^2.0.5
  flutter_svg: ^1.1.6
  skeletons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.png
  fonts:
    - family: Google Sans
      fonts:
        - asset: "assets/fonts/Google Sans/Regular.ttf"
          weight: 300
        - asset: "assets/fonts/Google Sans/Regular-Italic.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/Google Sans/Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Google Sans/Medium-Italic.ttf"
          weight: 500
          style: italic
        - asset: "assets/fonts/Google Sans/Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Google Sans/Bold-Italic.ttf"
          weight: 700
          style: italic
    - family: Red Hat
      fonts:
        - asset: "assets/fonts/Red Hat/Display-Light.ttf"
          weight: 300
        - asset: "assets/fonts/Red Hat/Display-Light.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/Red Hat/Display-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Red Hat/Display-Italic.ttf"
          weight: 400
          style: italic
        - asset: "assets/fonts/Red Hat/Display-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Red Hat/Display-MediumItalic.ttf"
          weight: 500
          style: italic
        - asset: "assets/fonts/Red Hat/Display-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Red Hat/Display-SemiBoldItalic.ttf"
          weight: 600
          style: italic
        - asset: "assets/fonts/Red Hat/Display-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Red Hat/Display-BoldItalic.ttf"
          weight: 700
          style: italic
        - asset: "assets/fonts/Red Hat/Display-ExtraBold.ttf"
          weight: 800
        - asset: "assets/fonts/Red Hat/Display-ExtraBoldItalic.ttf"
          weight: 800
          style: italic
        - asset: "assets/fonts/Red Hat/Display-Black.ttf"
          weight: 900
        - asset: "assets/fonts/Red Hat/Display-BlackItalic.ttf"
          weight: 900
          style: italic
    - family: Inter
      fonts:
        - asset: "assets/fonts/Inter/Thin.ttf"
          weight: 100
        - asset: "assets/fonts/Inter/ExtraLight.ttf"
          weight: 200
        - asset: "assets/fonts/Inter/Light.ttf"
          weight: 300
        - asset: "assets/fonts/Inter/Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Inter/Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Inter/SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Inter/Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Inter/ExtraBold.ttf"
          weight: 800
        - asset: "assets/fonts/Inter/Black.ttf"
          weight: 900